### ISSUE TITLE
('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by vaidyasm** [opendatagroup/fastscore-cli#2]
Couldn't add model or schema to freshly installed fastscore-cli

Reference: http://docs.opendatagroup.com/docs/getting-started-with-fastscore

```
# fastscore model list
('Connection aborted.', BadStatusLine("''",))
```

Also tried with the web UI. 
Shows error "Unable to save model" after a while.
Also shows error "Can't fetch models" after a while.

Searching similar issues on other repo hints at client attempting to parse empty string as HTTP response. No idea where to start looking for resolving this issue with fastscore.

**Comment by mahowald-odg** [comment]
Hi,
Please try the following REST commands:
```
curl -i -k https://localhost:8001/1/config
curl -i -k https://localhost:8002/1/health
curl -i -k https://localhost:8002/1/model
```
Replace localhost:8001 with the IP and port of the Connect container and localhost:8002 with the IP and port of the Model Manage container if you are using a different configuration than the one in the Getting Started Guide.

**Comment by vaidyasm** [comment]
Hi Matthew,

Responses to curl commands are pasted at:
https://pastebin.com/guXh6DLT

The last curl command has been running for 15 mins and hasn't completed.

For reference, config and docker compose yamls are pasted at
config.yaml: https://pastebin.com/QgHJsGq5
docker-compose.yml https://pastebin.com/ZLpSj1t5

volume "db" was created by running (once)
`# docker volume create --name=db`
before starting docker containers

**Comment by mahowald-odg** [comment]
It looks like you don't have any Kafka service available at port 9092. Please try either adding a Kafka server that listens on localhost:9092, or removing the lines
```
  pneumo:
    bootstrap:
      - localhost:9092
    topic: notify
    type: kafka
```
from your FastScore configuration file. 

Also, check that the database container (fastscore/model-manage-mysql) is accessible from the other containers on port 3306 at localhost. (Username: "root", password: "root").

**Comment by vaidyasm** [comment]
Yes, I do not have any Kafka services running. First run was done with pneumo section commented (before posting this issue) without success.

I've pinned down cause of the issue with the help of your hint. There was a mysql service listening on the host at port 3306. Although the host database was accessible with root un/pw, container processes were unable to work with the database running on host (missing fastscore schemas?). Stopping host database and restarting fastscore docker containers resolved the issue.

I'm very new to docker. Could isolating the containers from the host and configuring other containers to connect to database inside isolated container resolve such conflicts arising from having a database running on the host? Perhaps, changing `network_mode` to equivalent of isolated containers and mapping required ports to/from host to containers (connect, dashboard)?

Thanks
